// <auto-generated />
using System;
using KUKULCAN.SharedKernel.i18n.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KUKULCAN.SharedKernel.i18n.Migrations.MySql.Migrations
{
    [DbContext(typeof(I18NDbContext))]
    partial class I18NDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KUKULCAN.SharedKernel.i18n.Domain.Entities.CurrencyFormat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("int");

                    b.Property<string>("DecimalSeparator")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("LanguageCode");

                    b.Property<Guid?>("LanguageId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("NegativePattern")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("SpaceBetweenSymbolAndAmount")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<int>("SymbolPosition")
                        .HasColumnType("int");

                    b.Property<string>("ThousandsSeparator")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LanguageCode", "CurrencyCode")
                        .IsUnique()
                        .HasDatabaseName("UX_CurrencyFormats_Language_Currency");

                    b.ToTable("CurrencyFormats", (string)null);
                });

            modelBuilder.Entity("KUKULCAN.SharedKernel.i18n.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<int?>("DefaultLanguageMarker")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("DefaultLanguageMarker")
                        .HasComputedColumnSql("CASE WHEN `IsDefault` = 1 THEN 1 ELSE NULL END");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Languages_Code");

                    b.HasIndex("DefaultLanguageMarker")
                        .IsUnique()
                        .HasDatabaseName("UX_Languages_Default");

                    b.ToTable("Languages", (string)null);
                });

            modelBuilder.Entity("KUKULCAN.SharedKernel.i18n.Domain.Entities.LocaleConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<int>("CurrencyDecimalPlaces")
                        .HasColumnType("int");

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DateTimeFormat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("int");

                    b.Property<string>("DecimalSeparator")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<int>("FirstDayOfWeek")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("LanguageCode");

                    b.Property<Guid?>("LanguageId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("ShortDateFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ThousandsSeparator")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("TimeFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("UX_LocaleConfigurations_LanguageCode");

                    b.HasIndex("LanguageId")
                        .IsUnique();

                    b.ToTable("LocaleConfigurations", (string)null);
                });

            modelBuilder.Entity("KUKULCAN.SharedKernel.i18n.Domain.Entities.Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("Code");

                    b.Property<string>("Context")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("LanguageCode");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("IX_Translations_LanguageCode");

                    b.HasIndex("Code", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Translations_Code_Language");

                    b.ToTable("Translations", (string)null);
                });

            modelBuilder.Entity("KUKULCAN.SharedKernel.i18n.Domain.Entities.CurrencyFormat", b =>
                {
                    b.HasOne("KUKULCAN.SharedKernel.i18n.Domain.Entities.Language", null)
                        .WithMany("CurrencyFormats")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KUKULCAN.SharedKernel.i18n.Domain.Entities.LocaleConfiguration", b =>
                {
                    b.HasOne("KUKULCAN.SharedKernel.i18n.Domain.Entities.Language", null)
                        .WithOne("LocaleConfiguration")
                        .HasForeignKey("KUKULCAN.SharedKernel.i18n.Domain.Entities.LocaleConfiguration", "LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KUKULCAN.SharedKernel.i18n.Domain.Entities.Language", b =>
                {
                    b.Navigation("CurrencyFormats");

                    b.Navigation("LocaleConfiguration");
                });
#pragma warning restore 612, 618
        }
    }
}
