// <auto-generated />
using System;
using KUKULCAN.SharedKernel.i18n.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KUKULCAN.SharedKernel.i18n.Infrastructure.Migrations
{
    [DbContext(typeof(I18NDbContext))]
    [Migration("20260823143457_EnsureSingleDefaultLanguage")]
    partial class EnsureSingleDefaultLanguage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("i18n")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KUKULCAN.SharedKernel.i18n.Domain.Entities.CurrencyFormat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("integer");

                    b.Property<string>("DecimalSeparator")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("LanguageCode");

                    b.Property<Guid?>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NegativePattern")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("SpaceBetweenSymbolAndAmount")
                        .HasColumnType("boolean");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("SymbolPosition")
                        .HasColumnType("integer");

                    b.Property<string>("ThousandsSeparator")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LanguageCode", "CurrencyCode")
                        .IsUnique()
                        .HasDatabaseName("UX_CurrencyFormats_Language_Currency");

                    b.ToTable("CurrencyFormats", "i18n");
                });

            modelBuilder.Entity("KUKULCAN.SharedKernel.i18n.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Languages_Code");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("UX_Languages_Default")
                        .HasFilter("\"IsDefault\" = true");

                    b.ToTable("Languages", "i18n");
                });

            modelBuilder.Entity("KUKULCAN.SharedKernel.i18n.Domain.Entities.LocaleConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrencyDecimalPlaces")
                        .HasColumnType("integer");

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DateTimeFormat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("integer");

                    b.Property<string>("DecimalSeparator")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<int>("FirstDayOfWeek")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("LanguageCode");

                    b.Property<Guid?>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShortDateFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ThousandsSeparator")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("TimeFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("UX_LocaleConfigurations_LanguageCode");

                    b.HasIndex("LanguageId")
                        .IsUnique();

                    b.ToTable("LocaleConfigurations", "i18n");
                });

            modelBuilder.Entity("KUKULCAN.SharedKernel.i18n.Domain.Entities.Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("Code");

                    b.Property<string>("Context")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("LanguageCode");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("IX_Translations_LanguageCode");

                    b.HasIndex("Code", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Translations_Code_Language");

                    b.ToTable("Translations", "i18n");
                });

            modelBuilder.Entity("KUKULCAN.SharedKernel.i18n.Domain.Entities.CurrencyFormat", b =>
                {
                    b.HasOne("KUKULCAN.SharedKernel.i18n.Domain.Entities.Language", null)
                        .WithMany("CurrencyFormats")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KUKULCAN.SharedKernel.i18n.Domain.Entities.LocaleConfiguration", b =>
                {
                    b.HasOne("KUKULCAN.SharedKernel.i18n.Domain.Entities.Language", null)
                        .WithOne("LocaleConfiguration")
                        .HasForeignKey("KUKULCAN.SharedKernel.i18n.Domain.Entities.LocaleConfiguration", "LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KUKULCAN.SharedKernel.i18n.Domain.Entities.Language", b =>
                {
                    b.Navigation("CurrencyFormats");

                    b.Navigation("LocaleConfiguration");
                });
#pragma warning restore 612, 618
        }
    }
}
